name: Suggest a new resource
description: Propose a link/tool/resource to add
labels: [enhancement]
body:
  - type: input
    id: title
    attributes:
      label: Resource name
    validations:
      required: true
  - type: input
    id: url
    attributes:
      label: URL
    validations:
      required: true
  - type: dropdown
    id: category
    attributes:
      label: Category
      options:
        - Bedrock
        - Java
        - Android
        - iOS
        - Tools
        - Other
    validations:
      required: true
  - type: textarea
    id: notes
    attributes:
      label: Why should we add it?

